services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data-blog_db:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      args:
        - PORT=${BACKEND_PORT}
    restart: always
    environment:
      PORT: ${BACKEND_PORT}
      JWT_ACCESS: ${JWT_ACCESS}
      JWT_REFRESH: ${JWT_REFRESH}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      CLIENT_URL: http://localhost:5173
      NODE_ENV: production
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_HOST_URL=http://backend:${BACKEND_PORT}
        - NODE_ENV=production
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app

volumes:
  postgres_data-blog_db:
